# Generated by Django 5.0.6 on 2024-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
