# Generated by Django 5.0.6 on 2024-06-11 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='id_inventario',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
    ]
