# Generated by Django 5.0.6 on 2024-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_inventario_id_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_inventario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
